controller_list:
# -------------for gazebo UR5---------------------------------
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint

# -------------for gazebo gripper---------------------------------
  - name: gripper
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
#    action_ns: gripper_cmd
#    type: GripperCommand
    default: true
    joints: 
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3,
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
