# sensors:
#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /head_mount_kinect2/depth/filtered_points
#     max_range: 3.5
#     point_subsample: 1
#     padding_offset: 0.1
#     padding_scale: 1.0
#     filtered_cloud_topic: filtered_cloud
sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/aligned_depth_to_color/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 2.5
    shadow_threshold: 0.2  #0.35
    padding_scale: 4.0
    padding_offset: 0.03
    max_update_rate: 5.0
    filtered_cloud_topic: filtered_cloud
